# Generated by Django 6.0.3 on 2026-04-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0002_teller_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High-Priority'), ('delayed', 'Delayed')], default='normal', max_length=10),
        ),
    ]
