# Generated by Django 6.0.3 on 2026-04-26 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0004_service_prefix_teller_is_online_ticket_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['priority', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='queueing_ti_status_9a588a_idx',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High-Priority'), (2, 'Normal'), (3, 'Delayed')], default=2),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'service', 'priority', 'created_at'], name='queueing_ti_status_6f3ddc_idx'),
        ),
    ]
